# Generated by Django 6.0.7 on 2026-09-04 10:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(default='Kerala', max_length=100)),
                ('image_url', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PropertyAmenity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('listing_type', models.CharField(choices=[('buy', 'For Sale'), ('rent', 'For Rent')], default='buy', max_length=10)),
                ('property_type', models.CharField(choices=[('apartment', 'Apartment'), ('house', 'House/Villa'), ('plot', 'Plot/Land'), ('commercial', 'Commercial'), ('office', 'Office Space'), ('shop', 'Shop/Retail')], default='apartment', max_length=20)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('location_text', models.CharField(max_length=255)),
                ('city', models.CharField(default='trivandrum', max_length=100)),
                ('bedrooms', models.IntegerField(default=0)),
                ('bathrooms', models.IntegerField(default=0)),
                ('area_sqft', models.IntegerField(default=0)),
                ('furnishing', models.CharField(default='semi-furnished', max_length=50)),
                ('parking', models.CharField(default='Available', max_length=100)),
                ('status', models.CharField(default='Ready to Move', max_length=50)),
                ('posted_by', models.CharField(choices=[('Owner', 'Owner'), ('Builder', 'Builder'), ('Agent', 'Agent')], default='Owner', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('verified', models.BooleanField(default=True)),
                ('featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='properties', to=settings.AUTH_USER_MODEL)),
                ('amenities', models.ManyToManyField(blank=True, to='properties.propertyamenity')),
            ],
        ),
        migrations.CreateModel(
            name='PropertyImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.URLField()),
                ('is_primary', models.BooleanField(default=False)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='properties.property')),
            ],
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to=settings.AUTH_USER_MODEL)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='properties.property')),
            ],
            options={
                'unique_together': {('user', 'property')},
            },
        ),
    ]
